### ISSUE TITLE
"httplug" is not a valid alias

### ISSUE THREAD

**Issue by gigi** [php-http/httplug-flex-pack#4]
Hi!

Trying to install php-http via flex using 
```
composer require httplug
```

http://docs.php-http.org/en/latest/integrations/symfony-bundle.html#using-symfony-flex

```
 [UnexpectedValueException]
  "httplug" is not a valid alias.
```

Seems there is no such alias here https://flex.symfony.com/. Is it wrong docs or we should fix alias?)

**Comment by dbu** [comment]
thanks @gigi for bringing this to our attention! i will try to figure out whether there is some misconfiguration in the recipe or if we should adjust our documentation. meanwhile, you can `composer require httplug-bundle` to install. that name will for sure remain valid.

@Nyholm where are the flex alias defined? searching on flex.symfony.com it seems we currently are only available as httplug-bundle

**Comment by gigi** [comment]
@dbu strange, but only `composer require php-http/httplug-bundle` works

**Comment by dbu** [comment]
that is the name of the composer package, so it would not be using flex at all i fear. or am i mistaken? did you get some default configuration in your config/ folder?

**Comment by gigi** [comment]
Recipe is been processed for composer package `php-http/httplug-bundle`
```
Symfony operations: 1 recipe (7be06eb9e08e68a159b746833537dd37)
  - Configuring php-http/httplug-bundle (>=1.6): From github.com/symfony/recipes-contrib:master
``` 
Ive got `config/httplug.yaml` and `Http\HttplugBundle\HttplugBundle::class => ['all' => true],` in `config/bundles.php`

So bundle installed properly.

I was confused when just copy-pasted instruction from the docs and it doesn't work)

**Comment by Nyholm** [comment]
Flex aliases are just for official recipes. 

I updated that documentation pages a few months ago... why did I do this? https://github.com/php-http/documentation/pull/261

It should be the package name.

**Comment by dbu** [comment]
ah, okay. i thought they only took away the `http` alias... i created https://github.com/php-http/documentation/pull/266
